version: 2
defaults: &defaults
  macos:
    xcode: "9.0"
    environment:
      LANG: en_US.UTF-8
jobs:
  # prepare_environment:
  #   <<: *defaults
  #   steps:
  #     - checkout    
  #     - run: curl -sS https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash  
  #     # Due to a problem with Homebrew, see: https://github.com/Homebrew/brew/issues/991
  #     - run: brew update ; brew update
  #     - run: brew install swiftlint
  #     - run: bundle install
  test:
    <<: *defaults
    steps:
      - checkout      
      - run: bundle install
      # Only bootstrap if we have updated dependencies since our last cache.
      - run: pwd ; ls -all; scripts/bootstrap-if-needed.sh 
      - run: rake test
  test_integration_carthage:
    <<: *defaults
    steps:
      - checkout  
      - run: pwd ; ls -all; rake test:carthage
  build_demo:
    <<: *defaults
    steps:
      - run: curl -sS https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash           
      - checkout     
      - run: bundle install
      - run: pwd ; ls -all; cd Demo ; bundle exec pod repo update
      # Verbose to keep CI alive during long Specs repo setups.  
      - run: cd Demo ; bundle exec pod install --verbose
      - run: rake build_demo 
  danger_codecov:
    <<: *defaults
    steps:
      - run: brew install swiftlint
      - run: bundle install
      - run:
          command: |
            bundle exec danger
            bash <(curl -s https://codecov.io/bash) -J Moya                  
workflows:
  version: 2
  pr_build:
    jobs:
      - test
      - test_integration_carthage
      - build_demo     
      - danger_codecov:
          requires:
            - test
            - test_integration_carthage  
            - build_demo